# Generated by Django 4.2.2 on 2023-06-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MealSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meal_date", models.DateField()),
                ("breakfast", models.CharField(max_length=100)),
                ("lunch", models.CharField(max_length=100)),
                ("dinner", models.CharField(max_length=100)),
            ],
        ),
    ]
