# Generated by Django 4.2.2 on 2023-06-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="mealschedule",
            name="breakfast",
        ),
        migrations.RemoveField(
            model_name="mealschedule",
            name="dinner",
        ),
        migrations.RemoveField(
            model_name="mealschedule",
            name="lunch",
        ),
        migrations.AddField(
            model_name="mealschedule",
            name="breakfast_menus",
            field=models.ManyToManyField(
                blank=True, related_name="breakfast_schedules", to="meal.menu"
            ),
        ),
        migrations.AddField(
            model_name="mealschedule",
            name="dinner_menus",
            field=models.ManyToManyField(
                blank=True, related_name="dinner_schedules", to="meal.menu"
            ),
        ),
        migrations.AddField(
            model_name="mealschedule",
            name="lunch_menus",
            field=models.ManyToManyField(
                blank=True, related_name="lunch_schedules", to="meal.menu"
            ),
        ),
    ]
