# Generated by Django 4.2.2 on 2023-06-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meal", "0002_menu_remove_mealschedule_breakfast_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="allergic_notices",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="menu",
            name="calories",
            field=models.IntegerField(null=True),
        ),
    ]
